//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFExpress.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTask
    {
        public int EmployeeTaskID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime Deadline { get; set; }
        public string TaskName { get; set; }
    }
}
